# Generated by Django 3.1.6 on 2021-02-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('caption', models.CharField(max_length=1000)),
                ('url', models.URLField(max_length=10000)),
            ],
        ),
    ]
